# Generated by Django 4.2.1 on 2023-06-06 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCreation', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('categoryType', models.CharField(choices=[('TA', 'Танки'), ('GI', 'Хилы'), ('DD', 'ДД'), ('ME', 'Торговцы'), ('GU', 'Гилдмастеры'), ('QU', 'Квестгиверы'), ('BL', 'Кузнецы'), ('LE', 'Кожевники'), ('PO', 'Зельевары'), ('SP', 'Мастера заклинаний')], default='TA', max_length=2)),
                ('contentText', models.TextField()),
                ('contentImage', models.ImageField(blank=True, upload_to='')),
                ('contentFile', models.FileField(blank=True, upload_to='')),
                ('userAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataResponse', models.DateTimeField(auto_now_add=True)),
                ('contentResponse', models.TextField()),
                ('postsResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postsapp.post')),
                ('userResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
