# Generated by Django 4.2.1 on 2023-06-10 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import postsapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postsapp', '0002_remove_post_userauthor_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentFile',
            field=models.FileField(blank=True, upload_to=postsapp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentImage',
            field=models.ImageField(blank=True, upload_to=postsapp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
