# Generated by Django 4.2.1 on 2023-06-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0004_post_is_private_response_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='is_accepted',
            new_name='accepted',
        ),
    ]
